name = "Blackburn"
license = "MIT"
licenselink = "https://github.com/mayth/blackburn/blob/master/LICENSE.md"
description = "A clear, responsive theme constructed using Pure CSS from Yahoo"
homepage = "https://github.com/mayth/blackburn"
tags = ["blog", "personal", "purecss", "responsive"]
features = ["blog", "personal", "purecss", "responsive"]
min_version = 0.15

[author]
  name = "Mei Akizuru"
  homepage = "https://aquarite.info"

# If porting an existing theme
[original]
  name = "Blackburn"
  homepage = "https://github.com/yoshiharuyamashita/blackburn"
  repo = "https://github.com/yoshiharuyamashita/blackburn"
